### ISSUE TITLE
Consider making a tagged release

### ISSUE THREAD

**Issue by paulmaunders** [smiller171/ansible-user-management#10]
This looks like a nice simple yet effective role. 

Could you consider releasing a 'version' on github / Ansible galaxy? That way users can easily include it as a stable dependency in their project requirements.yml

e.g.

```
- name: scott.miller171.manage_users
  src: scott.miller171.manage_users
  version: 0.1.0
```

**Comment by smiller171** [comment]
To do this it looks like I just need to tag a version in Github, not edit my metadata, right?

**Comment by smiller171** [comment]
I've created a 1.0 tag and begun re-import into Galaxy. I think that should work but I'll leave this issue open for now.

**Comment by smiller171** [comment]
Version 1.0 was added in Galaxy
